# Generated by Django 4.1.7 on 2023-03-21 23:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('nome', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'especie',
            },
        ),
        migrations.CreateModel(
            name='Raca',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('nome', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'raca',
            },
        ),
        migrations.CreateModel(
            name='Veterinario',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('clinica', models.CharField(max_length=100)),
                ('celular', models.CharField(blank=True, max_length=14, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('celular', models.CharField(blank=True, max_length=14, null=True)),
                ('cpf', models.CharField(blank=True, max_length=14, null=True)),
                ('rg', models.CharField(blank=True, max_length=14, null=True)),
                ('rua', models.CharField(blank=True, max_length=14, null=True)),
                ('numero', models.CharField(blank=True, max_length=14, null=True)),
                ('complemento', models.CharField(blank=True, max_length=14, null=True)),
                ('bairro', models.CharField(blank=True, max_length=14, null=True)),
                ('cidade', models.CharField(blank=True, max_length=14, null=True)),
                ('uf', models.CharField(blank=True, choices=[('RJ', 'Rj'), ('ES', 'Es'), ('MG', 'Mg'), ('SP', 'Sp'), ('RS', 'Rs'), ('SC', 'Sc'), ('PR', 'Pr'), ('DF', 'Df'), ('GO', 'Go'), ('MT', 'Mt'), ('MS', 'Ms'), ('TO', 'To'), ('AM', 'Am'), ('PA', 'Pa'), ('AC', 'Ac'), ('RR', 'Rr'), ('RO', 'Ro'), ('AP', 'Ap'), ('MA', 'Ma'), ('PI', 'Pi'), ('CE', 'Ce'), ('RN', 'Rn'), ('PB', 'Pb'), ('PE', 'Pe'), ('AL', 'Al'), ('SE', 'Se'), ('BA', 'Ba')], default='RJ', max_length=14, null=True)),
                ('email', models.EmailField(blank=True, max_length=40, null=True)),
                ('observacao', models.CharField(blank=True, max_length=200, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tutor',
            },
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('sexo', models.CharField(choices=[('Macho', 'Macho'), ('Fêmea', 'Fêmea')], max_length=10)),
                ('idade', models.IntegerField(default=0)),
                ('observacao', models.CharField(blank=True, max_length=200, null=True)),
                ('especie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.especie')),
                ('raca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.raca')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meu_dono', to='core.tutor')),
            ],
            options={
                'db_table': 'pet',
            },
        ),
    ]
