# Generated by Django 4.1.7 on 2023-03-21 18:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('nome', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'especie',
            },
        ),
        migrations.CreateModel(
            name='Raca',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('nome', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'raca',
            },
        ),
        migrations.AlterField(
            model_name='tutor',
            name='observacao',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('sexo', models.CharField(choices=[('Macho', 'Macho'), ('Fêmea', 'Fêmea')], max_length=10)),
                ('idade', models.IntegerField(default=0)),
                ('observacao', models.CharField(blank=True, max_length=200, null=True)),
                ('especie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.especie')),
                ('raca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.raca')),
            ],
        ),
    ]
