# Generated by Django 4.1.7 on 2023-03-21 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_especie_raca_alter_tutor_observacao_pet'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='tutor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.tutor'),
        ),
    ]
