# Generated by Django 4.1.7 on 2023-03-21 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_pet_tutor'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='pet',
            table='pet',
        ),
    ]
